---
- name: My Arch Linux playbook
  hosts: '{{ group | default("laptop") }}'
  vars_prompt:
    - name: ansible_become_password
      prompt: 'Enter the root password'

  roles:
  - packages
  - suckless
  - config
