---
- name: Install packages from official repository
  ansible.builtin.include_tasks:
    file: install_apt_packages.yml

- name: Install discord
  ansible.builtin.include_tasks:
    file: install_discord.yml

- name: Install golang
  ansible.builtin.include_tasks:
    file: install_golang.yml

- name: Install kubectl
  ansible.builtin.include_tasks:
    file: install_kubectl.yml
