---
- name: Install packages from official repository
  become: true
  ansible.builtin.apt:
    package:
      - ansible
      - ansible-core
      - awscli
      - curl
      - darktable
      - dictd
      #- discord #should install via .deb pacakge
      - docker
      - dunst
      - feh
      - firefox-esr
      - gimp
      - git
      #- go #should install using go script
      - inkscape
      - jq
      #- kubectl
      - maim
      - mpv
      - neofetch
      - openssh-server
      - pass
      - pass-otp
      - python3
      - python3-pip
      - rclone
      - transmission-cli
      - unclutter
      - unzip
      - neovim
      - xbindkeys
      - xclip
      - zathura
      - zbar-tools
